config/routes.rb
IpadTracking::Application.routes.draw do
  devise_for :users
  root to: "welcome#index"
  resources :students
  resources :devices
  resources :notes
  resources :finances
  resources :admins

  get "/show/meraki/:serial", to: "devices#meraki", as: "meraki"

  get "/deassociate/:id", to: "devices#deassociate", as: "deassociate"
  get "/associate/:id", to: "devices#associate", as: "associate"

  get "/device/:id/check_in", to: "devices#check_in", as: "device_check_in"
  get "/device/:id/check_out", to: "devices#check_out", as: "device_check_out"

  post "/admin/import_all_submit", to: "admins#import_all_submit", as: "import_all_submit"
  get "/admin/import_all", to: "admins#import_all", as: "import_all"
  get "/admin/edit_admins", to: "admins#edit_admins", as: "edit_admins"
  post "/admin/update_admins", to: "admins#update_admins", as: "update_admins"
  get "/admin", to: "admins#index", as: "administrator"
  get "/admin/logs", to: "admins#logs", as: "admin_logs"
  get "/admin/export_students", to: "admins#export_students", as: "admin_export_students"
  get "/admin/devices_export", to: "admins#export_devices", as: "admin_export_devices"

  

  

end

app/views/admins/_log_navigation.html.erb
<TABLE border="0">
  <TR>
    <TD width="18" align="center">
<font size ="4">
<%= link_to "«", admin_logs_path(page: 1, q: "#{@search || ""}") %>
<% if @page > 1 %><%= link_to "‹", admin_logs_path(page: (@page-1), q: "#{@search || ""}") %><% else %>‹<% end %>
</font>
    </TD>
<% if @page-3 > 0 %>
    <TD width="12" align="center">
<%= @page-3 > 0 ? "..." : "" %>
    </TD>
<% end %>
<% if @page-2 >= 1 %>
    <TD width="16" align="center">
<%= link_to "#{@page-2}", admin_logs_path(page: (@page-2), q: "#{@search || ""}") %>
    </TD>
<% end %>
    <TD width="16" align="center">
<% if @page-1 >= 1 %><%= link_to "#{@page-1}", admin_logs_path(page: (@page-1), q: "#{@search || ""}") %><% end %>  
    </TD>
    <TD width="16" align="center">
<%= @page %>
    </TD>
    <TD width="16" align="center">
<% if @page+1 <= @last %><%= link_to "#{@page+1}", admin_logs_path(page: (@page+1), q: "#{@search || ""}") %><% end %>
    </TD>
    <TD width="16" align="center">
<% if @page+2 <= @last %><%= link_to "#{@page+2}", admin_logs_path(page: (@page+2), q: "#{@search || ""}") %><% end %>
    </TD>
    <TD width="12" align="center">
<%= @page+3 < @last ? "..." : "" %>
    </TD>
    <TD width="18" align="center">
<font size ="4">
<% if @page+1 <= @last %><%= link_to "›", admin_logs_path(page: (@page+1), q: "#{@search || ""}") %><% else %>›<% end %>
<%= link_to "»", admin_logs_path(page: @last, q: "#{@search || ""}") %>
</font>
    </TD>
  </TR>
</TABLE>

app/views/admins/edit_admins.html.erb
<H3>Edit Current Administrators:</H3>

<%= form_tag update_admins_path, multipart: true do %>
  <% User.all.each do |user| %>
    <% if user.admin && current_user == user %>
      <%= check_box_tag user.id, 'admin', true, disabled: true %> <%= user.email %> (You)<br>
    <% elsif user.admin %>
      <%= check_box_tag user.id, 'admin', true %> <%= user.email %><br>
    <% else %>
      <%= check_box_tag user.id, 'admin' %> <%= user.email %><br>
    <% end %>
  <% end %><br>
  <%= submit_tag "Update" %>
<% end %>

app/views/admins/import_all.html.erb
<h3>Import Students & Devices:</h3>
- This tool allows you to import Students, Devices or Both.<br>
- Uploads must be in <b>.CSV</b> format and fields must use the following field headers:<br>
- Valid Student fields are: <b><font color="red">id_number | grade_level | first_name | last_name | email | home_phone | current_school | parent_1_first | parent_1_last | parent_2_first | parent_2_last | parent_1_phone | parent_2_phone |
        parent_1_email | parent_2_email | policy_number | insurance_expiration |</font></b>
<br>- Valid Device fields are: <b><font color="blue"> serial_number | district_tag | device_type |</font></b><br>
    - Valid Note fields are: <b><font color="green"> note</font></b><br>
    <br>
<ul>
  <li>To import <b><font color="red">Students</font></b> you must include all <b><font color="red">Red</font></b> fields.</li>
  <li>To import <b><font color="blue">Devices</font></b> you must include all <b><font color="blue">Blue</font></b> fields.</li>
  <li>To import <b><font color="green">a Note</font></b> you must include all <b><font color="green">Green</font></b> fields.</li>
</ul>
- Red, Blue and Green items entered on the same line will automatically be linked together during the import process.<br>
<br>
<b>Import:</b>
<%= form_tag import_all_submit_path, multipart: true do %>
  <%= file_field_tag :file %><br>
  <%= submit_tag "Import" %>
<% end %>
<H4><B><font color="red">ALERT:</font> Once you press "Import" the website will seemingly hang. Do not navigate away from this page until you see "Students & Devices imported." The larger your file the longer the import will take.</B></H4>

app/views/admins/index.html.erb
<H3>Admin Tools:</H3>

<OL style="list-style-type: decimal" >
  <LI><%= link_to "Import All", import_all_path %></li>
  <LI><%= link_to "Edit Administrators", edit_admins_path %></LI>
  <LI><%= link_to "User Logs", admin_logs_path %></LI>
  <LI><%= link_to "Export Students", admin_export_students_path(format: "csv") %></LI>
  <LI><%= link_to "Export Devices", admin_export_devices_path(format: "csv") %></LI>
<OL>

app/views/admins/logs.html.erb
<H3>User Logs:</H3>
<% if @notes %>
  <ul>
  <% @notes.each do |note| %>
    <li><b><%= note.created_at.in_time_zone("Pacific Time (US & Canada)").asctime %>:</B> <%= note.note %> | <% if note.device %>Tag: <%= link_to "#{note.device.district_tag}", note.device %><% end %><% if note.student %><%= note.device && note.student ? " - " : "" %>ID: <%= link_to "#{note.student.id_number}", note.student %><% end %><% if note.user == current_user %> - <%= link_to "Delete Note", note, data: { confirm: "Are you sure you want to permanently delete this device?" }, method: :delete %><% end %></li>
  <% end %>
  </ul>
<% end %>
<%= render "log_navigation" %>