config/routes.rb
IpadTracking::Application.routes.draw do
  devise_for :users
  root to: "welcome#index"
  resources :students
  resources :devices
  resources :notes
  resources :finances
  resources :admins

  get "/show/meraki/:serial", to: "devices#meraki", as: "meraki"

  get "/deassociate/:id", to: "devices#deassociate", as: "deassociate"
  get "/associate/:id", to: "devices#associate", as: "associate"

  get "/device/:id/check_in", to: "devices#check_in", as: "device_check_in"
  get "/device/:id/check_out", to: "devices#check_out", as: "device_check_out"

  post "/admin/import_all_submit", to: "admins#import_all_submit", as: "import_all_submit"
  get "/admin/import_all", to: "admins#import_all", as: "import_all"
  get "/admin/edit_admins", to: "admins#edit_admins", as: "edit_admins"
  post "/admin/update_admins", to: "admins#update_admins", as: "update_admins"
  get "/admin", to: "admins#index", as: "administrator"
  get "/admin/logs", to: "admins#logs", as: "admin_logs"
  get "/admin/export_students", to: "admins#export_students", as: "admin_export_students"
  get "/admin/devices_export", to: "admins#export_devices", as: "admin_export_devices"

  

  

end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :devices
  has_many :notes
  has_many :finances

  validates :first_name, :last_name, :id_number, :grade_level, presence: true
  validates :id_number, uniqueness: true

  GRADE_LEVEL = [9, 10, 11, 12]
  INSURANCE = ["DLA", "Independent", "None"]

  default_scope { order("last_name, first_name") }

  def title_case
    if self.first_name != "" && self.last_name != ""
      self.first_name.downcase!
      self.last_name.downcase!

      f = first_name[0].upcase
      l = last_name[0].upcase
      self.first_name = f + self.first_name[1..-1]
      self.last_name = l + self.last_name[1..-1]
    end
  end

  def self.title_case_query query
    if query != ""
      query = query.downcase
      query = query[0].upcase + query[1..-1]
    else
      return nil
    end
  end

  def self.search query
    query = Student.title_case_query(query)
    where("first_name LIKE :query OR last_name LIKE :query OR id_number LIKE :query", query: "%#{query}%")
  end

  def self.no_devices_search #returns an array of student objects that do not have devices.
    no_devices = []
    Student.all.map do |student|
      if student.devices == []
        no_devices << student
      end
    end
    return no_devices
  end

  def self.import_all(file)
    CSV.foreach(file.path, headers: true, header_converters: :symbol) do |row|

      student = find_by(id_number: row[:id_number]) || Student.new
      parent_1_name = (row[:parent_1_first] || "") + " " + (row[:parent_1_last] || "")
      parent_2_name = (row[:parent_2_first] || "") + " " + (row[:parent_2_last] || "")

      student.attributes = row.to_hash.slice(:id_number, :grade_level, :first_name, :last_name, :email, :home_phone, :current_school, :parent_1_phone, :parent_2_phone,
        :parent_1_email, :parent_2_email, :policy_number, :insurance_expiration)
      student.parent_1_name = parent_1_name
      student.parent_2_name = parent_2_name

      if ["9", "10", "11", "12"].include?(student.grade_level.to_s)
        student.active = true
      else
        student.active = false
      end

      device = Device.find_by(serial_number: row[:serial_number]) || Device.new

      device.attributes = row.to_hash.slice(:device_type, :serial_number, :district_tag)

      if student.save
        # Note.create(student: student, note: "Student was imported/updated.")

        if row.to_hash.slice(:note)
          note = Note.new
          note.attributes = row.to_hash.slice(:note)
          note.student = student
          note.save
        end

        if device.save
          device.associate(student, nil)
        end
      end #if student.save

    end #CSV

  end #def end.

  def finance_total
    total = BigDecimal.new(0)
    finances.each do |finance|
      if finance.charge == true
        total -= finance.amount
      else
        total += finance.amount
      end
    end
    total
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  require 'csv'

  before_action :authenticate_user!
  before_action :require_admin

  def index #links will go 0, 20, 40, 60...
    @page = (params[:page] || 1).to_i
    @students = Student.where(active: true)[(@page-1)*20..((@page-1)*20+19)]
    @last = ((Student.all.length/20)+1).to_i

    @student_search = Student.new
    @search = params[:q]
    if params[:q]
      @students = (Student.search params[:q])
      if @students.length == 1
        redirect_to student_path(@students.first) and return
      end
      @last = ((@students.all.length/20)+1).to_i
      @students = @students[(@page-1)*20..((@page-1)*20+19)]
    end
  end

  def show
    @student = Student.find(params[:id])
    @devices = @student.devices
    @history = @student.notes

    @total = @student.finance_total

    @note = Note.new
    @finance = Finance.new

    @device_search = Device.new
    if params[:q]
      @devices_search = Device.search params[:q]
    end
  end

  def new
    @student = Student.new
  end

  def edit
    @student = Student.find(params[:id])
  end

  def create
    @student = Student.new student_params
    @student.title_case

    if @student.save
      Note.create(student: @student, note: "Student #{@student.id_number} was created.")
      redirect_to students_path, flash: {success: "Student was created."}
    else
      errors = ""
      @student.errors.full_messages.each do |message|
        errors += (" " + message + ".")
      end
      flash[:error] = "<B>ERROR:</B> #{errors}"
      render :new
    end
  end

  def update
    @student = Student.find(params[:id])
    if @student.update_attributes(student_params)
      redirect_to student_path(@student), flash: {success: "Student was updated."}
    else
      errors = ""
      @student.errors.full_messages.each do |message|
        errors += (" " + message + ".")
      end
      flash[:error] = "<B>ERROR:</B> #{errors}"
      render :edit
    end
  end

  def destroy
    Student.find(params[:id]).destroy

    redirect_to students_path, flash: {success: "Student was deleted."}
  end

  private

  def student_params
    params.require(:student).permit(:first_name, :last_name, :id_number, :grade_level, :insurance, :insurance_expiration,
                                    :current_school, :parent_1_name, :parent_1_phone, :parent_2_name,
                                    :parent_2_phone, :parent_1_email, :parent_2_email, :email, :home_phone, :policy_number)
  end

  def require_admin
    unless current_user.admin == true
      redirect_to root_path, flash: {error: "You are not authorized to perform that action."}
    end
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_errors.html.erb
<% @student.errors.full_messages.each do |message| %>
  <%= message %><br>
<% end %><br>

app/views/students/_form.html.erb
<%= form_for @student, class: "form-control" do |f| %>
  <div class="row">
    <div class="col-md-4">
    <P><B>Required:</B></P>
    <%= f.label :first_name, class: "form-label" %>
    <%= f.text_field :first_name, autofocus: true, class: "form-control" %><br>
    <%= f.label :last_name, class: "form-label" %>
    <%= f.text_field :last_name, class: "form-control" %><br>
    <%= f.label :id_number, class: "form-label" %>
    <%= f.text_field :id_number, class: "form-control" %><br>
    <%= f.label :grade_level, class: "form-label" %>
    <%= f.collection_select(:grade_level, Student::GRADE_LEVEL, :to_i, :to_i, {:include_blank => false}, {class: 'form-control'}) %><br>
    <%= f.label :email, class: "form-label" %>
    <%= f.text_field :email, class: "form-control" %><br>
    </div>
    <div class="col-md-4">
    <P><B>Optional:</B></P>
    <%= f.label :current_school, class: "form-label" %>
    <%= f.text_field :current_school, class: "form-control" %><br>
        <%= f.label :home_phone, class: "form-label" %>
    <%= f.text_field :home_phone, class: "form-control" %><br>
    <%= f.label :parent_1_name, class: "form-label" %>
    <%= f.text_field :parent_1_name, class: "form-control" %><br>
    <%= f.label :parent_1_phone, class: "form-label" %>
    <%= f.text_field :parent_1_phone, class: "form-control" %><br>
    <%= f.label :parent_1_email, class: "form-label" %>
    <%= f.text_field :parent_1_email, class: "form-control" %><br>
    <%= f.label :parent_2_name, class: "form-label" %>
    <%= f.text_field :parent_2_name, class: "form-control" %><br>
    <%= f.label :parent_2_phone, class: "form-label" %>
    <%= f.text_field :parent_2_phone, class: "form-control" %><br>
    <%= f.label :parent_2_email, class: "form-label" %>
    <%= f.text_field :parent_2_email, class: "form-control" %><br>
    <%= f.label :policy_number, class: "form-label" %>
    <%= f.text_field :policy_number, class: "form-control" %><br>
    <%= f.label :insurance_expiration, class: "form-label" %>
    <%= f.text_field :insurance_expiration, class: "form-control" %><br>
    </div>
  </div>

  <%= f.submit class: 'btn btn-primary'  %>
<% end %>

app/views/students/_navigation.html.erb
<TABLE border="0">
  <TR>
    <TD width="18" align="center">
<font size ="4">
<%= link_to "«", students_path(page: 1, q: "#{@search || ""}") %>
<% if @page > 1 %><%= link_to "‹", students_path(page: (@page-1), q: "#{@search || ""}") %><% else %>‹<% end %>
</font>
    </TD>
<% if @page-3 > 0 %>
    <TD width="12" align="center">
<%= @page-3 > 0 ? "..." : "" %>
    </TD>
<% end %>
<% if @page-2 >= 1 %>
    <TD width="16" align="center">
<%= link_to "#{@page-2}", students_path(page: (@page-2), q: "#{@search || ""}") %>
    </TD>
<% end %>
    <TD width="16" align="center">
<% if @page-1 >= 1 %><%= link_to "#{@page-1}", students_path(page: (@page-1), q: "#{@search || ""}") %><% end %>  
    </TD>
    <TD width="16" align="center">
<%= @page %>
    </TD>
    <TD width="16" align="center">
<% if @page+1 <= @last %><%= link_to "#{@page+1}", students_path(page: (@page+1), q: "#{@search || ""}") %><% end %>
    </TD>
    <TD width="16" align="center">
<% if @page+2 <= @last %><%= link_to "#{@page+2}", students_path(page: (@page+2), q: "#{@search || ""}") %><% end %>
    </TD>
    <TD width="12" align="center">
<%= @page+3 < @last ? "..." : "" %>
    </TD>
    <TD width="18" align="center">
<font size ="4">
<% if @page+1 <= @last %><%= link_to "›", students_path(page: (@page+1), q: "#{@search || ""}") %><% else %>›<% end %>
<%= link_to "»", students_path(page: @last, q: "#{@search || ""}") %>
</font>
    </TD>
  </TR>
</TABLE>

app/views/students/_student.html.erb
<%= link_to "#{student.first_name} #{student.last_name} (#{student.grade_level})", student %> ID: <%= student.id_number %>

app/views/students/edit.html.erb
<h1>Edit Student:</h1>
<HR>
<%= render 'form' %>

app/views/students/index.html.erb
<h1>Student List:</h1>
<%= link_to "New Student", new_student_path %>
<%= form_tag students_path, :method => :get, :class => "form-inline" do %>
  <%= text_field_tag :q, '',size: 30, autofocus: true, class: "form-control" %>
  <%= submit_tag "Search", class: 'btn btn-primary btn-sm' %>
<% end %>
<br>
<ul>
<% @students.each do |student| %>
  <li><%=render "student", student: student %></li>
<% end %>
</ul>

<%= render "navigation" %>

app/views/students/new.html.erb
<h1>New Student:</h1>
<HR>
<%= render 'form' %>

app/views/students/show.html.erb
<div class="row">
  <div class="col-md-6">
    <h3><%= @student.first_name %> <%= @student.last_name %> (<%= @student.grade_level %>) ID: <%= @student.id_number %></h3>
    <table class="table table-striped">
      <tr>
        <td>
          <B>E-Mail:</B>
        </td>
        <td>
          <%= @student.email %>
        </td>
        <td>
          <B>Home Phone:</B>
        </td>
        <td>
          <%= @student.home_phone %>
        </td>
      </tr>
      <tr>
        <td>
          <B>Insurance:</B>
        </td>
        <td>
          <%= @student.policy_number %> - <%= @student.insurance_expiration %>
        </td>
        <td>
          <B>Current School:</B>
        </td>
        <td>
          <%= @student.current_school %>
        </td>
      </tr>
      <tr>
        <td>
          <B>Parent 1:</B>
        </td>
        <td>
          <%= @student.parent_1_name %>
        </td>
        <td>
          <B>Phone:</B>
        </td>
        <td>
          <%= @student.parent_1_phone %>
        </td>
      </tr>
      <tr>
        <td>
          <B>Parent 2:</B>
        </td>
        <td>
          <%= @student.parent_2_name %>
        </td>
        <td>
          <B>Phone:</B>
        </td>
        <td>
          <%= @student.parent_2_phone %>
        </td>
      </tr>
      <tr>
        <td>
          <B>Parent 1 Email:</B>
        </td>
        <td>
          <%= @student.parent_1_email %>
        </td>
        <td>
          <B>Parent 2 Email:</B>
        </td>
        <td>
          <%= @student.parent_2_email %>
        </td>
      </tr>
    </table>
    <P>
      <%= link_to "Edit Student", edit_student_path(@student) %> |
      <%= link_to "Delete Student", @student, data: { confirm: "Are you sure you want to permanently delete this student?" }, method: :delete %>
    </P>

    <table class="table table-striped">
      <tr>
        <td>
          <%= form_tag student_path, method: :get, class: "form-inline" do %>
          <%= label_tag 'Device Search:' %>
          <%= text_field_tag :q, '',size: 10, class: "form-control inline" %>
          <%= submit_tag "Search", class: 'btn btn-mini' %>
          <% end %>

          <% if @devices_search %>
          <%= @devices_search.length > 0 ? "Results:" : "No Results Found." %>
          <ul>
            <% @devices_search.each do |device| %>
            <li><%= device.device_type %>: <%= link_to "#{device.serial_number}", device_path(device) %> - <%= device.district_tag %> | <%= link_to "Add Device", associate_path(device, student: @student), data: { confirm: "Add #{device.serial_number} #{device.district_tag} to user?" } %></li>
            <% end %>
          </ul>
          <% end %>
        </td>
      </tr>
    </table>

    <H3>Devices:</H3>
    <% if @devices.length > 0 %>
      <table class="table table-striped" border=0>
        <tr>
          <th>
            Type
          </th>
          <th>
            Serial
          </th>
          <th>
            Tag
          </th>
          <th>
            Check In/Out
          </th>
          <th>
            Remove
          </th>
        </tr>
        <% @devices.each do |device| %>
          <tr>
            <td class="centerContents">
              <%= device.device_type %>
            </td>
            <td>
              <%= link_to "#{device.serial_number}", device %>
            </td>
            <td>
              <%= device.district_tag %>
            </td>
            <td class="centerContents">
              <% if device.checked_in == true || device.checked_in == nil %>
                <%= link_to "Check Out", device_check_out_path(device), class: "btn btn-small btn-danger"  %>
              <% elsif device.checked_in == false %>
                <%= link_to "Check In", device_check_in_path(device), class: "btn btn-small btn-success"  %>
              <% end %>
            </td>
            <td class="centerContents">
              <%= link_to "X", deassociate_path(device), class: "btn btn-mini btn-danger" , data: { confirm: "Remove device from user?" } %>
            </td>
          </tr>
        <% end %>
      </table>
    <% else %>
    <li>None</li>
    <% end %>
  </div>

  <div class="col-md-6">
    <h3>Finance Information:</h3>
    <table class="table table-striped">
      <tr>
        <td>
          <B>Date:</B>
        </td>
        <td width=70%>
          <B>Note:</B>
        </td>
        <td>
          <B>Amount:</B>
        </td>
      </tr>
        <% @student.finances.each do |finance| %>
          <tr>
            <td>
              <%= finance.created_at.in_time_zone("Pacific Time (US & Canada)").strftime("%F") %>
            </td>
            <td>
              <%= finance.note %>
              <% if current_user.id == finance.user_id %>
                <%= link_to "Delete", finance, data: { confirm: "Are you sure you want to permanently delete this charge/credit for #{finance.amount}?" }, method: :delete %>
              <% end %>
            </td>
            <td>
              <% if finance.charge == true %>
                <font color='red'>-<%= number_to_currency(finance.amount) %></font>
              <% else %>
                <font color='green'><%= number_to_currency(finance.amount) %></font>
              <% end %>
            </td>
          </tr>
        <% end %>
      <tr>
        <td>
        </td>
        <td class="rightCell">
          Total:
        </td>
        <td>
          <% if @total < 0 %>
             <font color='red'><%= number_to_currency(@total) %></font>
          <% else %>
            <font color='green'><%= number_to_currency(@total) %></font>
          <% end %>
        </td>
      </tr>
    </table>

    <%= form_for @finance do |f| %>
    <div class="field">
    <table>
      <tr>
        <td class='centerCell'>
          <div class="btn-group">
            <%= f.radio_button :charge, 'true', :id=>"Charge", :style=>"display:none;" %>
            <label for="Charge" class="btn btn-danger">Charge</label>
            <%= f.radio_button :charge, 'false', :id=>"Credit", :style=>"display:none;" %>
            <label for="Credit" class="btn btn-success">Credit</label>
          </div>
        </td>
        <td class='centerCell'>
          <%= f.text_field :note, class: "form-control", placeholder: 'Note' %>
        </td>
        <td class='centerCell'>
          <%= f.text_field :amount, class: "form-control", placeholder: 'Amount', style: 'width: 80px;' %>
        </td>
        <td class='centerCell'>
          <%= f.submit "Add Transaction", class: 'btn btn-primary'  %>
        </td>
      </tr>
    </table>
      <%= f.hidden_field :student_id, value: @student.id %>
      <%= f.hidden_field :user_id, value: @current_user.id %>
    </div>
  </div>
  <% end %>

  <div class="col-md-12">
    <%= render "notes/history" %>
    <%= render "notes/add_student" %>
  </div>
</div>