config/routes.rb
IpadTracking::Application.routes.draw do
  devise_for :users
  root to: "welcome#index"
  resources :students
  resources :devices
  resources :notes
  resources :finances
  resources :admins

  get "/show/meraki/:serial", to: "devices#meraki", as: "meraki"

  get "/deassociate/:id", to: "devices#deassociate", as: "deassociate"
  get "/associate/:id", to: "devices#associate", as: "associate"

  get "/device/:id/check_in", to: "devices#check_in", as: "device_check_in"
  get "/device/:id/check_out", to: "devices#check_out", as: "device_check_out"

  post "/admin/import_all_submit", to: "admins#import_all_submit", as: "import_all_submit"
  get "/admin/import_all", to: "admins#import_all", as: "import_all"
  get "/admin/edit_admins", to: "admins#edit_admins", as: "edit_admins"
  post "/admin/update_admins", to: "admins#update_admins", as: "update_admins"
  get "/admin", to: "admins#index", as: "administrator"
  get "/admin/logs", to: "admins#logs", as: "admin_logs"
  get "/admin/export_students", to: "admins#export_students", as: "admin_export_students"
  get "/admin/devices_export", to: "admins#export_devices", as: "admin_export_devices"

  

  

end

app/models/device.rb
class Device < ActiveRecord::Base
  belongs_to :student
  has_many :notes

  validates :serial_number, :district_tag, uniqueness: true
  validates :device_type, :serial_number, :district_tag, presence: true

  DEVICES = ["iPad 10.2 7th Gen", "iPad 9.7 6th Gen", "iPad Pro 10.5", "iPad Pro", "iPad Air 2", "iPad Air", "iPad 4", "iPad 3", "MacBook Pro", "MacBook Air"]

  def associate(student, user)
    if self.update_attribute(:student_id, student.id)
      self.checked_in = false
      Note.create(student: student, user: user, device: self, note: "Device was added to student.")
      self.save
    end
  end

  def deassociate(user)
    student = self.student
    if self.update_attribute(:student_id, nil)
      self.checked_in = true
      Note.create(student: student, user: user, device: self, note: "Device was removed from student.")
      self.save
    end
  end

  def self.search query
    query.upcase!
    where("serial_number LIKE :query OR district_tag LIKE :query", query: "%#{query}%")
  end

  def self.export_serial
    CSV.generate do |csv|
      all.each do |device|
        csv << a=[device.serial_number]
      end
    end
  end

  def self.to_csv(options = {})
    unwanted_headers = ["id", "student_id", "created_at", "updated_at"]
    CSV.generate(options) do |csv|
      csv << column_names.delete_if{ |header| unwanted_headers.include?(header) }
      all.each do |device|
        csv << device.attributes.values_at(*column_names)
      end
    end
  end

end



# CODE FOR STUDENT SHOW PAGE REGARDING DEVICE CHECK IN/CHECKOUT
#----------------------------------------------------------------
# <%= form_for @finance do |f| %>
#   <div class="btn-group" data-toggle="buttons-radio">

#     <%= f.radio_button :charge, 'false', id: "Credit", style: "display:none;" %>
#     <label for="Credit" class="btn btn-mini btn-success">Check Out</label>
#   </div>
#   <%= f.text_field :note, placeholder: 'Note', style: 'font-size: 11px; height: 12px; width: 60px; vertical-align: top;' %>
#   <%= f.submit "Go", class: 'btn btn-mini btn-primary'  %>
# <% end %>

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin

  def index
    @page = (params[:page] || 1).to_i
    @devices = Device.all[(@page-1)*20..((@page-1)*20+19)]
    @last = ((Device.all.length/20)+1).to_i

    @device_search = Device.new
    @search = params[:q]
    if params[:q]
      @devices = Device.search params[:q]
      if @devices.length == 1
        redirect_to device_path(@devices.first) and return
      end
      @last = ((@devices.all.length/20)+1).to_i
      @devices = @devices[(@page-1)*20..((@page-1)*20+19)]
    end

    respond_to do |format|
      format.html
      format.csv { render text: Device.export_serial }
    end
  end

  def show
    @current_user = current_user
    @device = Device.find(params[:id])
    @history = @device.notes

    @student_search = Student.new
    if params[:q]
      @students_search = Student.search params[:q]
    end

    @note = Note.new
  end

  def new
    @device = Device.new
  end

  def create
    @device = Device.new device_params
    @device.serial_number.upcase!

    if @device.save #If it can save, redirects to movie path, otherwise renders new page again (and errors are displayed)
      Note.create(device: @device, note: "Device #{@device.serial_number} was added to inventory.")
      redirect_to devices_path, flash: {success: "Device was created."}
    else
      render :new
    end
  end

  def edit
    @device = Device.find(params[:id])
  end

  def update
    @device = Device.find(params[:id])
    serial = @device.serial_number
    device_type = @device.device_type
    district_tag = @device.district_tag
    if @device.update device_params
      Note.create(device: @device, note: "Device information was updated from Serial: #{serial}, Device: #{device_type}, District Tag: #{district_tag}.")
      redirect_to device_path(@device), flash: {success: "Device was updated."}
    else
      render :edit
    end
  end

  def meraki
    url = "https://n48.meraki.com/EUHSD-Systems-Ma/n/nuDCmcm/manage/pcc/list#q=" + params[:serial]
    redirect_to url
  end

  def check_out
    session[:return_to] ||= request.referer

    @device = Device.find(params[:id])
    @device.checked_in = false
    @device.save

    redirect_to session.delete(:return_to), flash: {success: "Device checked out." }  
  end

  def check_in
    session[:return_to] ||= request.referer

    @device = Device.find(params[:id])
    @device.checked_in = true
    @device.save

    redirect_to session.delete(:return_to), flash: {success: "Device checked in." }
  end

  def destroy
    Device.find(params[:id]).destroy
    
    redirect_to devices_path, flash: {success: "Device was deleted."}
  end

  # def search(params, student)
  #   @device = Device.new
  #   @devices = Device.search params[:device][:serial_number]

  #   redirect_to student
  # end

  def associate
    session[:return_to] ||= request.referer

    device = Device.find(params[:id])
    student = Student.find(params[:student])
    user = current_user

    if device.student
      redirect_to session.delete(:return_to), flash: {error: "Device #{device.device_type} #{device.serial_number} #{device.district_tag} already has an owner: #{device.student.id_number}"}
    else
      device.associate(student, user)
      redirect_to session.delete(:return_to), flash: {success: "Added #{device.device_type} #{device.serial_number} #{device.district_tag} to #{student.id_number}."}
    end
  end

  def deassociate
    session[:return_to] ||= request.referer

    device = Device.find(params[:id])
    student = device.student
    user = current_user
    device.deassociate(user)
    
    redirect_to session.delete(:return_to), flash: {success: "Removed #{device.device_type} #{device.serial_number} #{device.district_tag} from user."}
  end

  private

  def device_params
    params.require(:device).permit(:device_type, :serial_number, :district_tag)
  end

  def require_admin
    unless current_user.admin == true
      redirect_to root_path, flash: {error: "You are not authorized to perform that action."}
    end
  end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_device.html.erb
<%= device.device_type %> - <%= link_to "#{device.serial_number}", device_path(device) %> - <%= device.district_tag %>

app/views/devices/_errors.html.erb
<% @device.errors.full_messages.each do |message| %>
  <%= message %><br>
<% end %><br>

app/views/devices/_navigation.html.erb
<TABLE border="0">
  <TR>
    <TD width="18" align="center">
<font size ="4">
<%= link_to "«", devices_path(page: 1, q: "#{@search || ""}") %>
<% if @page > 1 %><%= link_to "‹", devices_path(page: (@page-1), q: "#{@search || ""}") %><% else %>‹<% end %>
</font>
    </TD>
<% if @page-3 > 0 %>
    <TD width="12" align="center">
<%= @page-3 > 0 ? "..." : "" %>
    </TD>
<% end %>
<% if @page-2 >= 1 %>
    <TD width="16" align="center">
<%= link_to "#{@page-2}", devices_path(page: (@page-2), q: "#{@search || ""}") %>
    </TD>
<% end %>
    <TD width="16" align="center">
<% if @page-1 >= 1 %><%= link_to "#{@page-1}", devices_path(page: (@page-1), q: "#{@search || ""}") %><% end %>  
    </TD>
    <TD width="16" align="center">
<%= @page %>
    </TD>
    <TD width="16" align="center">
<% if @page+1 <= @last %><%= link_to "#{@page+1}", devices_path(page: (@page+1), q: "#{@search || ""}") %><% end %>
    </TD>
    <TD width="16" align="center">
<% if @page+2 <= @last %><%= link_to "#{@page+2}", devices_path(page: (@page+2), q: "#{@search || ""}") %><% end %>
    </TD>
    <TD width="12" align="center">
<%= @page+3 < @last ? "..." : "" %>
    </TD>
    <TD width="18" align="center">
<font size ="4">
<% if @page+1 <= @last %><%= link_to "›", devices_path(page: (@page+1), q: "#{@search || ""}") %><% else %>›<% end %>
<%= link_to "»", devices_path(page: @last, q: "#{@search || ""}") %>
</font>
    </TD>
  </TR>
</TABLE>

app/views/devices/edit.html.erb
<h1>Edit Device:</h1>
<%= form_for @device do |f| %>

<div class="field">
    <%= f.label :device_type %>
    <%= f.collection_select :device_type, Device::DEVICES, :to_s, :to_s, :include_blank => false %>
    <%= f.label :serial_number %>
    <%= f.text_field :serial_number %>
    <%= f.label :district_tag %>
    <%= f.text_field :district_tag %>
</div>

<div id="error_explanation">
    <% if @device.errors.any? %>
      <%= render "errors", object: f.object %>
    <% end %>
</div>

  <%= f.submit class: 'btn btn-primary'  %>
<% end %>

app/views/devices/index.html.erb
<h1>Device List:</h1>
<%= link_to "New Device", new_device_path %>
<%= form_tag devices_path, :method => :get, :class => "form-inline" do %>
  <%= text_field_tag :q, '',size: 30, autofocus: true, class: "form-control" %>
  <%= submit_tag "Search", class: 'btn btn-primary btn-sm' %>
<% end %>
<br>
<ul>
<% @devices.each do |device| %>
  <li><%= render "device", device: device %></li>
<% end %>
</ul>
<%= render "navigation" %>

app/views/devices/new.html.erb
<h1>New Device:</h1>
<div class="form-group">
<%= form_for @device, class: "form-control" do |f| %>

<div class="col-md-4">
    <%= f.label :device_type, class: "control-label" %>
    <%= f.collection_select(:device_type, Device::DEVICES, :to_s, :to_s, {:include_blank => false}, {class: 'form-control'}) %><br>
    <%= f.label :serial_number, class: "form-label" %>
    <%= f.text_field :serial_number, class: "form-control" %><br>
    <%= f.label :district_tag, class: "form-label" %>
    <%= f.text_field :district_tag, class: "form-control" %><br>

<div id="error_explanation">
    <% if @device.errors.any? %>
      <%= render "errors", object: f.object %>
    <% end %>
</div>

  <%= f.submit class: 'btn btn-primary'  %>
<% end %>

</div>
</div>

app/views/devices/show.html.erb
<H2>Device: <%= "#{@device.device_type}" %></H2>
<%= link_to "Edit", edit_device_path(@device), data: { confirm: "Are you sure you want to EDIT this device?" } %> - <%= link_to "Permanently Delete", @device, data: { confirm: "Are you sure you want to PERMANENTLY DELETE this device?" }, method: :delete %><br>
<b>Serial Number:</b> <%= "#{@device.serial_number}" %> <%= link_to image_tag("meraki.png", :size => "32x32"), meraki_path(serial: @device.serial_number), target: "_blank" %><br>
<b>District Tag:</b> <%= "#{@device.district_tag}" %><br>
<b>Status:</b>
  <% if @device.checked_in || @device.checked_in == nil %>
    <FONT COLOR="Green">Checked In</FONT> <%= link_to "Check Out", device_check_out_path(@device), class: "btn btn-mini btn-danger"  %>
  <% else %>
    <FONT COLOR="Red">Checked Out</FONT> <%= link_to "Check In", device_check_in_path(@device), class: "btn btn-mini btn-success"  %>
  <% end %><br>
<b>Current User:</b>
<% if @device.student %>
  <%= render "students/student", student: @device.student %> - <%= link_to "Remove", deassociate_path(@device), data: { confirm: "Remove device from user?" } %>
  <br>
  <br>
<% else %>
  None.<br>
  <br>
  <%= form_tag device_path, method: :get, class: "form-inline" do %>
    <%= label_tag 'Student Search:' %>
    <%= text_field_tag :q, '',size: 10, class: "form-control", autofocus: true %>
    <%= submit_tag "Search", class: 'btn btn-mini' %>
  <% end %>

  <% if @students_search %>
    <%= @students_search.length > 0 ? "Results:" : "No Results Found." %>
    <ul>
      <% @students_search.each do |student| %>
        <li><%= render "students/student", student: student %> - <%= link_to "Add to Student", associate_path(@device, student: student), data: { confirm: "Add #{student.first_name} #{student.last_name} - #{student.id_number} to device?" } %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>
<%= render "notes/history" %>
<%= render "notes/add_device" %>