config/routes.rb
IpadTracking::Application.routes.draw do
  devise_for :users
  root to: "welcome#index"
  resources :students
  resources :devices
  resources :notes
  resources :finances
  resources :admins

  get "/show/meraki/:serial", to: "devices#meraki", as: "meraki"

  get "/deassociate/:id", to: "devices#deassociate", as: "deassociate"
  get "/associate/:id", to: "devices#associate", as: "associate"

  get "/device/:id/check_in", to: "devices#check_in", as: "device_check_in"
  get "/device/:id/check_out", to: "devices#check_out", as: "device_check_out"

  post "/admin/import_all_submit", to: "admins#import_all_submit", as: "import_all_submit"
  get "/admin/import_all", to: "admins#import_all", as: "import_all"
  get "/admin/edit_admins", to: "admins#edit_admins", as: "edit_admins"
  post "/admin/update_admins", to: "admins#update_admins", as: "update_admins"
  get "/admin", to: "admins#index", as: "administrator"
  get "/admin/logs", to: "admins#logs", as: "admin_logs"
  get "/admin/export_students", to: "admins#export_students", as: "admin_export_students"
  get "/admin/devices_export", to: "admins#export_devices", as: "admin_export_devices"

  

  

end

app/views/layouts/_flash_notices.html.erb
<div id="flash_messages">
  <% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> alert-dismissible" role="alert">
      <button class="close" data-dismiss="alert">×</button>
        <%= message.html_safe %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <title>DLA: Device Invetory</title>
    <%= csrf_meta_tags %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <!-- Javascripts ================================================== -->
    <!-- Placed in the head of the document so turbolinks can do it's think without interference -->
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "DLA: Tracking", root_path, :class => "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Students", students_path %></li>
            <li><%= link_to "Devices", devices_path %></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <% if current_user.admin %>
                <li><%= link_to "Admin", administrator_path %></font></li>
              <% end %>
              <li><%= link_to "Profile", edit_user_registration_path %></li>
            <% end %>
            <% if user_signed_in? %>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Login", new_user_session_path %>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

<!--Container typically starts here-->
      <% if content_for?(:jumbotron) %>
        <div class="jumbotron">
        <br>
        <br>
          <div class="container">
            <%= render "layouts/flash_notices" %>
            <%= yield :jumbotron %>
          </div>
        </div>
        <div class="container">
      <% else %>
        <br>
        <br>
        <br>
        <div class="container">
        <%= render "layouts/flash_notices" %>
      <% end %>

      <%= yield %>

        </div>
        <div class="container">
          <div class="row">
            <hr>
            <p>&copy; P 2018</p>
          </div>
        </div>
 <!-- /container -->

  </body>
</html>